name: Build and publish to pages branch

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build static export
        run: npm run build

      - name: Add .nojekyll (optional)
        run: touch out/.nojekyll

      - name: Publish out/ to pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: out
          clean: true
          single-commit: true
